apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: jhub-sticky-conf
  namespace: jhub
spec:
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 3600  # 1 hora de memoria